name = "yangbingyi"
type = "javascript"
# workers_dev = true
compatibility_date = "2022-01-26"
route = "api.ranwei.dev/*"
zone_id = "10a94d72247d5cafadd0d0b960a4b8db"
account_id = "78dba5fdfff6440c608bdf8ca1a5dd70"

[vars]
WORKERS_RS_VERSION = "0.0.7"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
