name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install wrangler
        run: |
          npm i @cloudflare/wrangler -g
      - name: Publish
        run: |
          CF_API_TOKEN=${{ secrets.SU_SHAN_SHAN_CF_API_TOKEN }} wrangler publish
